"""Canonical IDS payload schemas for ingestion, datasets, and future serving.

Sensor-specific field names terminate at this package boundary.  Downstream
code consumes only these explicit contracts, addressing the undocumented and
non-reproducible feature semantics found during the Step 1 audit.
"""
from .common import FlowCounters, NetworkEndpoint, WindowDataQuality
from .datasets import (
    DatasetFreezeManifest,
    DatasetFreezeVerificationReport,
    DatasetSource,
    PcapEvidenceFile,
)
from .events import (
    CANONICAL_EVENT_ADAPTER,
    CanonicalNetworkEvent,
    FlowEnd,
    FlowStart,
    FlowUpdate,
    NetworkEvent,
    SensorHealthEvent,
    SignatureEvent,
    parse_network_event_json,
)
from .events_v2 import CanonicalNetworkEventV2, FlowEndV2
from .exact_time_v2 import (
    DECIMAL_PRECISION,
    DECIMAL_SCALE,
    ExactDecimalConversionError,
    ExactDecimalSeconds22,
    canonical_seconds,
    canonical_seconds_from_unscaled,
    decimal_to_unscaled,
    unscaled_from_canonical,
)
from .features import FeatureWindow
from .feature_window_v2 import CanonicalFeatureWindowV2, FeatureWindowV2
from .feature_window_protocol_v2 import (
    FeatureWindowPartitionReportV2,
    FeatureWindowRunReportV2,
    FeatureWindowSpecificationV2,
)
from .replay import (
    ZeekDeterminismPolicy,
    ZeekLogArtifact,
    ZeekOutputPolicy,
    ZeekReplayRunReport,
    ZeekReplaySpecification,
    ZeekRuntimePin,
)
from .labels import (
    AuthoritativeSource,
    EndpointSelector,
    EventLabel,
    LabelAssignmentProvenance,
    LabelManifest,
    LabelRule,
    LocalScheduleInterval,
)
from .zeek_normalization_run_v2 import (
    ZeekNormalizationRunReportV2,
    ZeekPartitionNormalizationReportV2,
    ZeekRejectionCountV2,
    ZeekRejectionReasonV2,
    ZeekRejectionSpanV2,
)
from .zeek_normalization_v2 import (
    ZeekConnLogMappingV2,
    ZeekEventEnvelopePolicyV2,
    ZeekFieldMappingV2,
    ZeekNormalizationContextV2,
    ZeekNormalizationSpecificationV2,
    ZeekParserBoundaryPolicyV2,
    ZeekProvenancePolicyV2,
    ZeekTemporalEvidenceProfileV2,
    ZeekTemporalPolicyV2,
    ZeekUnsupportedRecordPolicyV2,
)
from .zeek_normalization import (
    ZeekConnLogMapping,
    ZeekEventEnvelopePolicy,
    ZeekFieldMapping,
    ZeekNormalizationContext,
    ZeekNormalizationSpecification,
    ZeekOrderingPolicy,
    ZeekParserBoundaryPolicy,
    ZeekProvenancePolicy,
    ZeekReplayReportBinding,
    ZeekSourceCoordinate,
    ZeekTimestampPolicy,
    ZeekUnsupportedRecordPolicy,
)

__all__ = [
    "CANONICAL_EVENT_ADAPTER",
    "AuthoritativeSource",
    "CanonicalFeatureWindowV2",
    "CanonicalNetworkEvent",
    "CanonicalNetworkEventV2",
    "DECIMAL_PRECISION",
    "DECIMAL_SCALE",
    "DatasetFreezeManifest",
    "DatasetFreezeVerificationReport",
    "DatasetSource",
    "EndpointSelector",
    "EventLabel",
    "ExactDecimalConversionError",
    "ExactDecimalSeconds22",
    "FeatureWindow",
    "FeatureWindowPartitionReportV2",
    "FeatureWindowRunReportV2",
    "FeatureWindowSpecificationV2",
    "FeatureWindowV2",
    "FlowCounters",
    "FlowEnd",
    "FlowEndV2",
    "FlowStart",
    "FlowUpdate",
    "LabelAssignmentProvenance",
    "LabelManifest",
    "LabelRule",
    "LocalScheduleInterval",
    "NetworkEndpoint",
    "NetworkEvent",
    "PcapEvidenceFile",
    "SensorHealthEvent",
    "SignatureEvent",
    "WindowDataQuality",
    "ZeekDeterminismPolicy",
    "ZeekLogArtifact",
    "ZeekOutputPolicy",
    "ZeekReplayRunReport",
    "ZeekReplaySpecification",
    "ZeekRuntimePin",
    "ZeekConnLogMapping",
    "ZeekConnLogMappingV2",
    "ZeekEventEnvelopePolicy",
    "ZeekEventEnvelopePolicyV2",
    "ZeekFieldMapping",
    "ZeekFieldMappingV2",
    "ZeekNormalizationContext",
    "ZeekNormalizationContextV2",
    "ZeekNormalizationRunReportV2",
    "ZeekNormalizationSpecification",
    "ZeekNormalizationSpecificationV2",
    "ZeekOrderingPolicy",
    "ZeekParserBoundaryPolicy",
    "ZeekParserBoundaryPolicyV2",
    "ZeekPartitionNormalizationReportV2",
    "ZeekProvenancePolicy",
    "ZeekProvenancePolicyV2",
    "ZeekRejectionCountV2",
    "ZeekRejectionReasonV2",
    "ZeekRejectionSpanV2",
    "ZeekReplayReportBinding",
    "ZeekSourceCoordinate",
    "ZeekTemporalEvidenceProfileV2",
    "ZeekTemporalPolicyV2",
    "ZeekTimestampPolicy",
    "ZeekUnsupportedRecordPolicy",
    "ZeekUnsupportedRecordPolicyV2",
    "canonical_seconds",
    "canonical_seconds_from_unscaled",
    "decimal_to_unscaled",
    "parse_network_event_json",
    "unscaled_from_canonical",
]
