"""MB4 canonical persistence for the Monday Benign track.

Isolation
---------
This module writes **only** into ``mb4_canonical``. It never issues DDL or DML
against ``m4_canonical``, ``m6_canonical``, or the legacy ``public`` schema, and
every foreign key it relies on stays inside ``mb4_canonical``. M chain
identities appear only as recorded values for audit.

Safety ordering, learned from the M4 data-loss incident
-------------------------------------------------------
1. ``assert_expected_database`` runs before *any* statement that can write. It
   compares ``current_database()`` against a name the caller must pass
   explicitly; there is no default that could silently target production.
2. ``verify_mb4_schema`` proves the four target tables exist with the columns
   and constraints the MB4 contract requires, before a single row is inserted.
3. ``verify_frozen_mb3_report`` proves the published MB3 report is intact and
   self-consistent, before the run row is created.
4. The partial unique index ``ux_mb4_runs_verified_report`` makes a second
   *verified* materialization of the same MB3 report fail loudly at the storage
   layer. The adapter also checks for it explicitly and raises a typed error.

Determinism
-----------
Events are **not** copied from any other table. The adapter re-invokes
``StrictZeekJsonLineParserV2`` and ``StrictZeekConnFlowEndNormalizerV2`` over the
MB2 Monday ``conn.log`` under the frozen MB3 protocol, so every ``event_id`` is
regenerated by the same UUID5 derivation MB3 used. Equality is then *proven*, not
assumed: the independently recomputed canonical event-stream digest must equal
the frozen MB3 value, otherwise the run is marked ``failed`` and nothing is
declared verified.
"""
from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone
from hashlib import sha256
import json
import os
from pathlib import Path
from typing import Any, Final, Literal
from uuid import UUID, uuid4

from pydantic import Field, model_validator
from typing import Annotated

from modules.detection.src.contracts import (
    NonNegativeInt,
    StrictIdentifier,
    StrictModel,
    UtcDateTime,
    VersionString,
)
from modules.detection.src.ingestion.zeek_json_v2 import StrictZeekJsonLineParserV2
from modules.detection.src.lineage.monday_benign_normalization import (
    BoundMondayBenignNormalizationSpecification,
    load_and_bind_monday_benign_normalization_specification,
)
from modules.detection.src.normalization.zeek_conn_v2 import (
    StrictZeekConnFlowEndNormalizerV2,
    ZeekRecordRejectionV2,
)
from modules.detection.src.normalization.zeek_pipeline_v2 import (
    _canonical_event_bytes,
    _canonical_rejection_bytes,
)
from modules.detection.src.schemas.datasets import Sha256Digest
from modules.detection.src.schemas.events_v2 import FlowEndV2
from modules.detection.src.schemas.exact_time_v2 import ExactDecimalSeconds22
from modules.detection.src.schemas.monday_benign_normalization import (
    MB3_EVENT_ID_NAMESPACE,
    MB3_REPORT_RELATIVE_PATH,
    MondayBenignNormalizationRunReport,
)
from modules.detection.src.schemas.monday_benign_replay import MONDAY_OUTPUT_PARTITION
from modules.detection.src.schemas.zeek_normalization import ZeekSourceCoordinate
from modules.detection.src.schemas.zeek_normalization_v2 import (
    ZeekNormalizationContextV2,
)


MB4_SCHEMA: Final[str] = "mb4_canonical"
MB4_REPORT_RELATIVE_PATH: Final[str] = (
    "artifacts/reports/mb4_monday_benign_materialization_run.json"
)
MB4_DDL_FILE_NAME: Final[str] = "schema_mb.sql"
MB4_REPORT_VERSION: Final[str] = "1.0.0"
_INSERT_BATCH_SIZE: Final[int] = 5_000

_REQUIRED_TABLES: Final[tuple[str, ...]] = (
    "flow_end_events",
    "materialization_runs",
    "rejection_counts",
    "rejection_spans",
)
_REQUIRED_EVENT_CONSTRAINTS: Final[tuple[str, ...]] = (
    "ck_mb4_events_causal_order",
    "ck_mb4_events_exact_end",
    "ck_mb4_events_monday_partition",
    "ck_mb4_events_ports",
    "ux_mb4_events_source_coordinate",
)
_EXACT_NUMERIC_COLUMNS: Final[tuple[str, ...]] = (
    "event_duration",
    "event_end_time",
    "event_start_time",
    "ingested_at",
    "record_available_time",
)


class MondayBenignMaterializationError(RuntimeError):
    """MB4 materialization cannot proceed or could not be verified."""


class MondayBenignDuplicateVerifiedRunError(MondayBenignMaterializationError):
    """A verified MB4 materialization of this frozen MB3 report already exists."""


class MondayBenignDatabaseGuardError(MondayBenignMaterializationError):
    """The connection does not target the explicitly expected database."""


# ---------------------------------------------------------------------------
# Published MB4 report contract
# ---------------------------------------------------------------------------


class MondayBenignMaterializationReport(StrictModel):
    """Immutable evidence that MB4 reproduced the frozen MB3 event stream."""

    report_version: VersionString
    verification_status: Literal["verified"]
    track: Literal["monday_benign"]
    run_id: UUID
    target_database: StrictIdentifier
    target_schema: Literal["mb4_canonical"]
    output_partition: StrictIdentifier

    mb3_report_content_sha256: Sha256Digest
    mb3_report_file_sha256: Sha256Digest
    mb3_protocol_sha256: Sha256Digest
    mb3_event_stream_sha256: Sha256Digest
    mb3_rejection_audit_stream_sha256: Sha256Digest
    mb1_manifest_sha256: Sha256Digest
    mb2_specification_sha256: Sha256Digest
    mb2_replay_report_content_sha256: Sha256Digest
    mb3_event_id_namespace: UUID

    materialized_event_stream_sha256: Sha256Digest
    materialized_rejection_stream_sha256: Sha256Digest

    record_available_time: ExactDecimalSeconds22
    ingested_at: ExactDecimalSeconds22

    total_processed_record_count: NonNegativeInt
    total_accepted_record_count: NonNegativeInt
    total_rejected_record_count: NonNegativeInt
    persisted_event_count: NonNegativeInt
    persisted_rejection_span_count: NonNegativeInt
    persisted_rejection_count_rows: NonNegativeInt
    rejection_counts: Annotated[
        tuple[tuple[str, int], ...],
        Field(default_factory=tuple),
    ]

    started_at: UtcDateTime
    completed_at: UtcDateTime

    @model_validator(mode="after")
    def validate_report(self) -> "MondayBenignMaterializationReport":
        """Require MB coordinates, digest equality, and coherent totals."""
        if self.output_partition != MONDAY_OUTPUT_PARTITION:
            raise ValueError(f"MB4 partition must be {MONDAY_OUTPUT_PARTITION}")
        if self.mb3_event_id_namespace != MB3_EVENT_ID_NAMESPACE:
            raise ValueError(f"MB4 namespace must be {MB3_EVENT_ID_NAMESPACE}")
        if self.materialized_event_stream_sha256 != self.mb3_event_stream_sha256:
            raise ValueError(
                "MB4 cannot be verified: recomputed event stream digest differs "
                "from the frozen MB3 value"
            )
        if self.materialized_rejection_stream_sha256 != (
            self.mb3_rejection_audit_stream_sha256
        ):
            raise ValueError(
                "MB4 cannot be verified: recomputed rejection digest differs "
                "from the frozen MB3 value"
            )
        if self.total_processed_record_count != (
            self.total_accepted_record_count + self.total_rejected_record_count
        ):
            raise ValueError("MB4 totals do not cover the source")
        if self.persisted_event_count != self.total_accepted_record_count:
            raise ValueError(
                "MB4 persisted event count differs from the accepted count"
            )
        if sum(count for _, count in self.rejection_counts) != (
            self.total_rejected_record_count
        ):
            raise ValueError("MB4 rejection counts do not cover rejections")
        if self.completed_at < self.started_at:
            raise ValueError("completed_at cannot precede started_at")
        return self

    def content_sha256(self) -> str:
        """Return a formatting-independent identity for the MB4 run."""
        payload = json.dumps(
            self.model_dump(mode="json"),
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=True,
        ).encode("utf-8")
        return sha256(payload).hexdigest()


# ---------------------------------------------------------------------------
# Frozen MB3 verification gate
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class VerifiedMondayBenignReport:
    """Result of verifying the published MB3 report before any write."""

    report: MondayBenignNormalizationRunReport
    report_content_sha256: str
    report_file_sha256: str
    protocol_sha256: str
    event_stream_sha256: str
    rejection_audit_stream_sha256: str


def verify_frozen_mb3_report(
    repository_root: str | Path,
    report_relative_path: str = MB3_REPORT_RELATIVE_PATH,
) -> VerifiedMondayBenignReport:
    """Verify the published MB3 report is intact and self-consistent."""
    root = Path(repository_root).resolve(strict=True)
    path = root / report_relative_path
    if not path.is_file():
        raise MondayBenignMaterializationError(f"MB3 report not found: {path}")
    raw = path.read_bytes()
    report = MondayBenignNormalizationRunReport.model_validate_json(
        raw.decode("utf-8")
    )
    if report.verification_status != "verified":
        raise MondayBenignMaterializationError("MB3 report is not verified")
    if report.track != "monday_benign":
        raise MondayBenignMaterializationError("MB3 report is not the MB track")
    if len(report.partition_reports) != 1:
        raise MondayBenignMaterializationError("MB3 report must hold one partition")
    partition = report.partition_reports[0]
    if partition.output_partition != MONDAY_OUTPUT_PARTITION:
        raise MondayBenignMaterializationError(
            f"MB3 report partition must be {MONDAY_OUTPUT_PARTITION}"
        )
    if report.event_id_namespace != MB3_EVENT_ID_NAMESPACE:
        raise MondayBenignMaterializationError("MB3 report namespace mismatch")
    return VerifiedMondayBenignReport(
        report=report,
        report_content_sha256=report.content_sha256(),
        report_file_sha256=sha256(raw).hexdigest(),
        protocol_sha256=report.protocol_sha256,
        event_stream_sha256=report.canonical_event_stream_sha256,
        rejection_audit_stream_sha256=report.rejection_audit_stream_sha256,
    )


# ---------------------------------------------------------------------------
# Connection, database guard, schema contract
# ---------------------------------------------------------------------------


def monday_benign_pg_settings(database: str) -> dict[str, Any]:
    """Return connection parameters for one explicitly named database."""
    return {
        "host": os.getenv("POSTGRES_HOST", "localhost"),
        "port": int(os.getenv("POSTGRES_PORT", "5432")),
        "dbname": database,
        "user": os.getenv("POSTGRES_USER", "cybersentinel"),
        "password": os.getenv("POSTGRES_PASSWORD", "cybersentinel"),
    }


def get_monday_benign_connection(database: str, connect_timeout: int = 5):
    """Connect to one explicitly named database. There is no default name."""
    if not database:
        raise MondayBenignDatabaseGuardError(
            "MB4 requires an explicit target database name"
        )
    import psycopg

    return psycopg.connect(
        connect_timeout=connect_timeout, **monday_benign_pg_settings(database)
    )


def assert_expected_database(conn, expected_database: str) -> str:
    """Refuse to continue unless ``current_database()`` equals the expectation.

    This is the guard whose absence caused the M4 production data loss. It runs
    before any statement capable of writing.
    """
    with conn.cursor() as cur:
        cur.execute("SELECT current_database()")
        row = cur.fetchone()
    actual = row[0] if row else None
    if actual != expected_database:
        raise MondayBenignDatabaseGuardError(
            f"MB4 refuses to write: connected to {actual!r}, "
            f"expected {expected_database!r}"
        )
    return actual


def _strip_sql_comments(ddl: str) -> str:
    """Return the DDL with ``--`` line comments removed.

    The isolation guard below must test executable statements, not prose. The
    MB4 DDL header deliberately names ``m4_canonical`` and ``m6_canonical`` to
    document that it never touches them, so a naive substring check on the raw
    text produces a false positive.
    """
    lines = []
    for line in ddl.splitlines():
        marker = line.find("--")
        lines.append(line if marker == -1 else line[:marker])
    return "\n".join(lines)


def ensure_mb4_schema(conn) -> None:
    """Apply schema_mb.sql. Every statement is CREATE ... IF NOT EXISTS."""
    ddl_path = Path(__file__).resolve().parent / MB4_DDL_FILE_NAME
    ddl = ddl_path.read_text(encoding="utf-8")
    executable = _strip_sql_comments(ddl)
    for forbidden in ("m4_canonical", "m6_canonical"):
        if forbidden in executable:
            raise MondayBenignMaterializationError(
                f"MB4 DDL must never reference {forbidden} in a statement"
            )
    with conn.cursor() as cur:
        cur.execute(ddl)
    conn.commit()


def verify_mb4_schema(conn) -> None:
    """Prove the target schema matches the MB4 contract before any insert."""
    with conn.cursor() as cur:
        cur.execute(
            "SELECT table_name FROM information_schema.tables "
            "WHERE table_schema = %s ORDER BY table_name",
            (MB4_SCHEMA,),
        )
        tables = tuple(row[0] for row in cur.fetchall())
        if tables != _REQUIRED_TABLES:
            raise MondayBenignMaterializationError(
                f"MB4 schema tables mismatch: expected {_REQUIRED_TABLES}, "
                f"found {tables}"
            )

        cur.execute(
            "SELECT column_name, numeric_precision, numeric_scale "
            "FROM information_schema.columns "
            "WHERE table_schema = %s AND table_name = 'flow_end_events' "
            "AND column_name = ANY(%s) ORDER BY column_name",
            (MB4_SCHEMA, list(_EXACT_NUMERIC_COLUMNS)),
        )
        numeric = tuple(cur.fetchall())
        if len(numeric) != len(_EXACT_NUMERIC_COLUMNS):
            raise MondayBenignMaterializationError(
                "MB4 temporal columns are incomplete"
            )
        for name, precision, scale in numeric:
            if (precision, scale) != (38, 22):
                raise MondayBenignMaterializationError(
                    f"MB4 column {name} must be NUMERIC(38,22), "
                    f"found NUMERIC({precision},{scale})"
                )

        cur.execute(
            "SELECT conname FROM pg_constraint "
            "WHERE conrelid = %s::regclass ORDER BY conname",
            (f"{MB4_SCHEMA}.flow_end_events",),
        )
        constraints = {row[0] for row in cur.fetchall()}
        missing = tuple(
            name for name in _REQUIRED_EVENT_CONSTRAINTS if name not in constraints
        )
        if missing:
            raise MondayBenignMaterializationError(
                f"MB4 event table is missing constraints: {missing}"
            )

        # No foreign key may leave mb4_canonical.
        cur.execute(
            """
            SELECT c.conname, n.nspname
            FROM pg_constraint c
            JOIN pg_class t ON t.oid = c.confrelid
            JOIN pg_namespace n ON n.oid = t.relnamespace
            WHERE c.contype = 'f'
              AND c.conrelid IN (
                  SELECT oid FROM pg_class
                  WHERE relnamespace = %s::regnamespace
              )
            """,
            (MB4_SCHEMA,),
        )
        foreign = tuple(cur.fetchall())
        offending = tuple(
            (name, schema) for name, schema in foreign if schema != MB4_SCHEMA
        )
        if offending:
            raise MondayBenignMaterializationError(
                f"MB4 foreign keys must stay inside {MB4_SCHEMA}: {offending}"
            )


# ---------------------------------------------------------------------------
# SQL
# ---------------------------------------------------------------------------


_INSERT_RUN_SQL = f"""
INSERT INTO {MB4_SCHEMA}.materialization_runs (
    run_id, mb3_report_content_sha256, mb3_report_file_sha256,
    mb3_protocol_sha256, mb3_event_stream_sha256,
    mb3_rejection_audit_stream_sha256,
    mb1_manifest_sha256, mb2_specification_sha256,
    mb2_replay_report_content_sha256, mb3_event_id_namespace,
    status, started_at
) VALUES (
    %(run_id)s, %(mb3_report_content_sha256)s, %(mb3_report_file_sha256)s,
    %(mb3_protocol_sha256)s, %(mb3_event_stream_sha256)s,
    %(mb3_rejection_audit_stream_sha256)s,
    %(mb1_manifest_sha256)s, %(mb2_specification_sha256)s,
    %(mb2_replay_report_content_sha256)s, %(mb3_event_id_namespace)s,
    %(status)s, %(started_at)s
)
"""

_UPDATE_RUN_SQL = f"""
UPDATE {MB4_SCHEMA}.materialization_runs
SET status = %(status)s,
    completed_at = %(completed_at)s,
    total_processed_record_count = %(total_processed_record_count)s,
    total_accepted_record_count = %(total_accepted_record_count)s,
    total_rejected_record_count = %(total_rejected_record_count)s,
    materialized_event_stream_sha256 = %(materialized_event_stream_sha256)s,
    materialized_rejection_stream_sha256 = %(materialized_rejection_stream_sha256)s
WHERE run_id = %(run_id)s
"""

_INSERT_EVENT_SQL = f"""
INSERT INTO {MB4_SCHEMA}.flow_end_events (
    event_id, mb4_run_id, sensor_id, sensor_run_id, capture_id,
    dataset_snapshot_id, model_release_id, normalizer_version, pipeline_version,
    schema_version, event_version, feature_version, sensor_version,
    event_type, sensor_type,
    event_start_time, event_duration, event_end_time,
    record_available_time, ingested_at,
    conversation_id, source_ip, source_port, destination_ip, destination_port,
    transport, service,
    source_packets, destination_packets, source_bytes, destination_bytes,
    connection_state, termination_reason,
    output_partition, physical_line_number, event_bytes_sha256
) VALUES (
    %(event_id)s, %(mb4_run_id)s, %(sensor_id)s, %(sensor_run_id)s,
    %(capture_id)s,
    %(dataset_snapshot_id)s, %(model_release_id)s, %(normalizer_version)s,
    %(pipeline_version)s,
    %(schema_version)s, %(event_version)s, %(feature_version)s,
    %(sensor_version)s,
    %(event_type)s, %(sensor_type)s,
    %(event_start_time)s, %(event_duration)s, %(event_end_time)s,
    %(record_available_time)s, %(ingested_at)s,
    %(conversation_id)s, %(source_ip)s, %(source_port)s, %(destination_ip)s,
    %(destination_port)s,
    %(transport)s, %(service)s,
    %(source_packets)s, %(destination_packets)s, %(source_bytes)s,
    %(destination_bytes)s,
    %(connection_state)s, %(termination_reason)s,
    %(output_partition)s, %(physical_line_number)s, %(event_bytes_sha256)s
)
"""

_INSERT_SPAN_SQL = f"""
INSERT INTO {MB4_SCHEMA}.rejection_spans (
    mb4_run_id, output_partition, first_physical_line_number,
    last_physical_line_number, reason, fields
) VALUES (
    %(mb4_run_id)s, %(output_partition)s, %(first_physical_line_number)s,
    %(last_physical_line_number)s, %(reason)s, %(fields)s
)
"""

_INSERT_COUNT_SQL = f"""
INSERT INTO {MB4_SCHEMA}.rejection_counts (
    mb4_run_id, output_partition, reason, count
) VALUES (
    %(mb4_run_id)s, %(output_partition)s, %(reason)s, %(count)s
)
"""

_CHECK_VERIFIED_RUN_SQL = f"""
SELECT run_id FROM {MB4_SCHEMA}.materialization_runs
WHERE mb3_report_content_sha256 = %(mb3_report_content_sha256)s
  AND status = 'verified'
"""


def _flow_end_row(
    event: FlowEndV2,
    run_id: UUID,
    source: ZeekSourceCoordinate,
    event_bytes_sha256: str,
) -> dict[str, Any]:
    """Map one FlowEndV2 to its MB4 row, verbatim, with no reinterpretation."""
    provenance = event.provenance
    return {
        "event_id": str(provenance.event_id),
        "mb4_run_id": str(run_id),
        "sensor_id": provenance.sensor_id,
        "sensor_run_id": provenance.sensor_run_id,
        "capture_id": provenance.capture_id,
        "dataset_snapshot_id": provenance.dataset_snapshot_id,
        "model_release_id": provenance.model_release_id,
        "normalizer_version": provenance.normalizer_version,
        "pipeline_version": provenance.pipeline_version,
        "schema_version": event.schema_version,
        "event_version": event.event_version,
        "feature_version": event.feature_version,
        "sensor_version": event.sensor_version,
        "event_type": event.event_type,
        "sensor_type": event.sensor_type,
        # Canonical fixed-scale strings go straight to NUMERIC(38,22).
        # psycopg passes str to NUMERIC untouched; no float is ever created.
        "event_start_time": event.event_start_time,
        "event_duration": event.event_duration,
        "event_end_time": event.event_end_time,
        "record_available_time": event.record_available_time,
        "ingested_at": event.ingested_at,
        "conversation_id": event.conversation_id,
        "source_ip": str(event.source.ip),
        "source_port": event.source.port,
        "destination_ip": str(event.destination.ip),
        "destination_port": event.destination.port,
        "transport": event.transport,
        "service": event.service,
        "source_packets": event.counters.source_packets,
        "destination_packets": event.counters.destination_packets,
        "source_bytes": event.counters.source_bytes,
        "destination_bytes": event.counters.destination_bytes,
        "connection_state": event.connection_state,
        "termination_reason": event.termination_reason,
        "output_partition": source.output_partition,
        "physical_line_number": source.physical_line_number,
        "event_bytes_sha256": event_bytes_sha256,
    }


@dataclass(frozen=True, slots=True)
class MondayBenignMaterializationOutcome:
    """Accumulated MB4 materialization evidence."""

    run_id: UUID
    processed: int
    accepted: int
    rejected: int
    persisted_events: int
    persisted_spans: int
    persisted_counts: int
    rejection_counts: tuple[tuple[str, int], ...]
    materialized_event_stream_sha256: str
    materialized_rejection_stream_sha256: str
    started_at: datetime
    completed_at: datetime


class MondayBenignMaterializationAdapter:
    """Re-normalize the MB2 Monday conn.log and persist into mb4_canonical."""

    def __init__(
        self,
        repository_root: str | Path,
        bound: BoundMondayBenignNormalizationSpecification,
        verified: VerifiedMondayBenignReport,
        expected_database: str,
    ) -> None:
        self._root = Path(repository_root).resolve(strict=True)
        self._bound = bound
        self._verified = verified
        self._expected_database = expected_database
        self._specification = bound.specification
        self._parser = StrictZeekJsonLineParserV2()
        self._normalizer = StrictZeekConnFlowEndNormalizerV2(self._specification)

    @classmethod
    def from_repository(
        cls,
        repository_root: str | Path,
        expected_database: str,
    ) -> "MondayBenignMaterializationAdapter":
        """Bind MB3 and verify its published report before any connection."""
        root = Path(repository_root).resolve(strict=True)
        bound = load_and_bind_monday_benign_normalization_specification(root)
        verified = verify_frozen_mb3_report(root)
        if verified.protocol_sha256 != bound.specification_sha256:
            raise MondayBenignMaterializationError(
                "published MB3 report does not match the bound MB3 protocol"
            )
        return cls(root, bound, verified, expected_database)

    def _conn_log_path(self) -> Path:
        binding = self._specification.replay_reports[0]
        return (
            self._root
            / self._specification.mb2_output_root
            / binding.output_partition
            / binding.supported_log.log_name
        ).resolve(strict=True)

    def materialize(self, conn) -> MondayBenignMaterializationOutcome:
        """Persist the Monday partition, then prove digest equality with MB3."""
        assert_expected_database(conn, self._expected_database)
        verify_mb4_schema(conn)

        report = self._verified.report
        binding = self._specification.replay_reports[0]
        artifact = binding.supported_log
        partition = binding.output_partition
        if partition != MONDAY_OUTPUT_PARTITION:
            raise MondayBenignMaterializationError(
                f"MB4 partition must be {MONDAY_OUTPUT_PARTITION}"
            )

        with conn.cursor() as cur:
            cur.execute(
                _CHECK_VERIFIED_RUN_SQL,
                {
                    "mb3_report_content_sha256": (
                        self._verified.report_content_sha256
                    )
                },
            )
            existing = cur.fetchone()
        if existing is not None:
            raise MondayBenignDuplicateVerifiedRunError(
                "a verified MB4 materialization of this MB3 report already "
                f"exists: run_id={existing[0]}"
            )

        run_id = uuid4()
        started_at = datetime.now(timezone.utc)
        with conn.cursor() as cur:
            cur.execute(
                _INSERT_RUN_SQL,
                {
                    "run_id": str(run_id),
                    "mb3_report_content_sha256": (
                        self._verified.report_content_sha256
                    ),
                    "mb3_report_file_sha256": self._verified.report_file_sha256,
                    "mb3_protocol_sha256": self._verified.protocol_sha256,
                    "mb3_event_stream_sha256": self._verified.event_stream_sha256,
                    "mb3_rejection_audit_stream_sha256": (
                        self._verified.rejection_audit_stream_sha256
                    ),
                    "mb1_manifest_sha256": self._bound.m1_manifest_sha256,
                    "mb2_specification_sha256": (
                        self._bound.mb2_specification_sha256
                    ),
                    "mb2_replay_report_content_sha256": (
                        self._bound.mb2_replay_report_content_sha256
                    ),
                    "mb3_event_id_namespace": str(
                        self._specification.provenance.event_id_namespace
                    ),
                    "status": "running",
                    "started_at": started_at,
                },
            )
        conn.commit()

        event_digest = sha256()
        rejection_digest = sha256()
        rejection_counts: Counter[str] = Counter()
        spans: list[dict[str, Any]] = []
        processed = accepted = rejected = 0
        batch: list[dict[str, Any]] = []

        try:
            with self._conn_log_path().open("rb") as stream, conn.cursor() as cur:
                for line_number, line in enumerate(stream, start=1):
                    processed = line_number
                    source = ZeekSourceCoordinate(
                        output_partition=partition,
                        replay_report_content_sha256=binding.report_content_sha256,
                        log_name="conn.log",
                        source_log_sha256=artifact.sha256,
                        reported_record_count=artifact.record_count,
                        physical_line_number=line_number,
                    )
                    context = ZeekNormalizationContextV2(
                        protocol_sha256=self._bound.specification_sha256,
                        source=source,
                        record_available_time=report.record_available_time,
                        ingested_at=report.ingested_at,
                    )
                    try:
                        record = self._parser.parse_line(line, source)
                        event = self._normalizer.normalize_conn(record, context)
                    except ZeekRecordRejectionV2 as rejection:
                        rejected += 1
                        rejection_counts[rejection.reason] += 1
                        payload = _canonical_rejection_bytes(source, rejection)
                        rejection_digest.update(payload)
                        if (
                            spans
                            and spans[-1]["last_physical_line_number"] + 1
                            == line_number
                            and spans[-1]["reason"] == rejection.reason
                            and spans[-1]["fields"] == list(rejection.fields)
                        ):
                            spans[-1]["last_physical_line_number"] = line_number
                        else:
                            spans.append(
                                {
                                    "mb4_run_id": str(run_id),
                                    "output_partition": partition,
                                    "first_physical_line_number": line_number,
                                    "last_physical_line_number": line_number,
                                    "reason": rejection.reason,
                                    "fields": list(rejection.fields),
                                }
                            )
                        continue

                    accepted += 1
                    payload = _canonical_event_bytes(event)
                    event_digest.update(payload)
                    batch.append(
                        _flow_end_row(
                            event, run_id, source, sha256(payload).hexdigest()
                        )
                    )
                    if len(batch) >= _INSERT_BATCH_SIZE:
                        cur.executemany(_INSERT_EVENT_SQL, batch)
                        batch.clear()
                if batch:
                    cur.executemany(_INSERT_EVENT_SQL, batch)
                    batch.clear()

                if spans:
                    cur.executemany(_INSERT_SPAN_SQL, spans)
                count_rows = [
                    {
                        "mb4_run_id": str(run_id),
                        "output_partition": partition,
                        "reason": reason,
                        "count": count,
                    }
                    for reason, count in sorted(rejection_counts.items())
                ]
                if count_rows:
                    cur.executemany(_INSERT_COUNT_SQL, count_rows)
            conn.commit()

            materialized_events = event_digest.hexdigest()
            materialized_rejections = rejection_digest.hexdigest()
            if materialized_events != self._verified.event_stream_sha256:
                raise MondayBenignMaterializationError(
                    "recomputed MB4 event stream digest differs from MB3: "
                    f"{materialized_events} != {self._verified.event_stream_sha256}"
                )
            if materialized_rejections != (
                self._verified.rejection_audit_stream_sha256
            ):
                raise MondayBenignMaterializationError(
                    "recomputed MB4 rejection digest differs from MB3"
                )

            completed_at = datetime.now(timezone.utc)
            with conn.cursor() as cur:
                cur.execute(
                    _UPDATE_RUN_SQL,
                    {
                        "run_id": str(run_id),
                        "status": "verified",
                        "completed_at": completed_at,
                        "total_processed_record_count": processed,
                        "total_accepted_record_count": accepted,
                        "total_rejected_record_count": rejected,
                        "materialized_event_stream_sha256": materialized_events,
                        "materialized_rejection_stream_sha256": (
                            materialized_rejections
                        ),
                    },
                )
            conn.commit()
        except BaseException:
            conn.rollback()
            try:
                with conn.cursor() as cur:
                    cur.execute(
                        _UPDATE_RUN_SQL,
                        {
                            "run_id": str(run_id),
                            "status": "failed",
                            "completed_at": datetime.now(timezone.utc),
                            "total_processed_record_count": processed,
                            "total_accepted_record_count": accepted,
                            "total_rejected_record_count": rejected,
                            "materialized_event_stream_sha256": None,
                            "materialized_rejection_stream_sha256": None,
                        },
                    )
                conn.commit()
            except Exception:  # pragma: no cover - best-effort audit trail
                conn.rollback()
            raise

        return MondayBenignMaterializationOutcome(
            run_id=run_id,
            processed=processed,
            accepted=accepted,
            rejected=rejected,
            persisted_events=accepted,
            persisted_spans=len(spans),
            persisted_counts=len(rejection_counts),
            rejection_counts=tuple(sorted(rejection_counts.items())),
            materialized_event_stream_sha256=materialized_events,
            materialized_rejection_stream_sha256=materialized_rejections,
            started_at=started_at,
            completed_at=completed_at,
        )

    def build_report(
        self,
        outcome: MondayBenignMaterializationOutcome,
    ) -> MondayBenignMaterializationReport:
        """Bind a successful outcome to the immutable MB4 report contract."""
        report = self._verified.report
        return MondayBenignMaterializationReport(
            report_version=MB4_REPORT_VERSION,
            verification_status="verified",
            track="monday_benign",
            run_id=outcome.run_id,
            target_database=self._expected_database,
            target_schema=MB4_SCHEMA,
            output_partition=MONDAY_OUTPUT_PARTITION,
            mb3_report_content_sha256=self._verified.report_content_sha256,
            mb3_report_file_sha256=self._verified.report_file_sha256,
            mb3_protocol_sha256=self._verified.protocol_sha256,
            mb3_event_stream_sha256=self._verified.event_stream_sha256,
            mb3_rejection_audit_stream_sha256=(
                self._verified.rejection_audit_stream_sha256
            ),
            mb1_manifest_sha256=self._bound.m1_manifest_sha256,
            mb2_specification_sha256=self._bound.mb2_specification_sha256,
            mb2_replay_report_content_sha256=(
                self._bound.mb2_replay_report_content_sha256
            ),
            mb3_event_id_namespace=(
                self._specification.provenance.event_id_namespace
            ),
            materialized_event_stream_sha256=(
                outcome.materialized_event_stream_sha256
            ),
            materialized_rejection_stream_sha256=(
                outcome.materialized_rejection_stream_sha256
            ),
            record_available_time=report.record_available_time,
            ingested_at=report.ingested_at,
            total_processed_record_count=outcome.processed,
            total_accepted_record_count=outcome.accepted,
            total_rejected_record_count=outcome.rejected,
            persisted_event_count=outcome.persisted_events,
            persisted_rejection_span_count=outcome.persisted_spans,
            persisted_rejection_count_rows=outcome.persisted_counts,
            rejection_counts=outcome.rejection_counts,
            started_at=outcome.started_at,
            completed_at=outcome.completed_at,
        )


def write_immutable_mb4_report(
    report: MondayBenignMaterializationReport,
    path: str | Path,
) -> str:
    """Publish the MB4 report immutably; return the written-byte hash.

    Mirrors the frozen publication policy: refuses to overwrite, exclusive
    create into a staging name, ``flush`` + ``os.fsync``, then atomic rename.
    """
    destination = Path(path)
    if destination.exists():
        raise FileExistsError(f"MB4 report already exists: {destination}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    payload = report.model_dump_json(indent=2).encode("utf-8") + b"\n"
    temporary = destination.with_name(f".{destination.name}.tmp")
    if temporary.exists():
        raise FileExistsError(f"MB4 report staging path exists: {temporary}")
    try:
        with temporary.open("xb") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, destination)
    except BaseException:
        if temporary.exists():
            temporary.unlink()
        raise
    return sha256(payload).hexdigest()
